services:
  database:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres_pwd
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    depends_on:
      - database
    container_name: lavurso-backend
    restart: unless-stopped
    build: 
      context: ./lavurso-backend
      args:
       POSTGRES_PASSWORD: lavurso_pwd
       POSTGRES_USER: lavurso
       POSTGRES_DATABASE: lavurso
    ports:
      - 8888:8080
  frontend:
    container_name: lavurso-frontend
    restart: unless-stopped
    build: ./lavurso-frontend
    ports:
      - 9000:9000
