services:
  database:
    image: postgres:15beta3-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    image: lavurso-backend
    depends_on:
      - database
    container_name: lavurso-backend
    restart: unless-stopped
    build: ./lavurso-backend
    ports:
      - 127.0.0.1:8888:8080
  frontend:
    image: lavurso-frontend
    container_name: lavurso-frontend
    restart: unless-stopped
    build: ./lavurso-frontend
#   volumes:
#     - ./lavurso-frontend:/app
    ports:
      - 127.0.0.1:9000:9000
