services:
  database:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres_pwd
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    depends_on:
      - database
    container_name: lavurso-backend
    restart: unless-stopped
    build: ./lavurso-backend
    environment:
      BACKEND_CORS_EXTRA_ALLOWED_ORIGIN: http://debian.local:9000 # this is your public facing front-end URI eg. https://lavurso.org
      POSTGRES_PASSWORD: lavurso_pwd
      POSTGRES_USER: lavurso
      POSTGRES_DATABASE: lavurso
    ports:
      - 8888:8080
  frontend:
    container_name: lavurso-frontend
    restart: unless-stopped
    build: ./lavurso-frontend
    environment:
      BACKEND_URI: http://debian.local:8888 # This is your back-end url,
    ports:
      - 9000:9000 # changing public facing port requires changing BACKEND_CORS_EXTRA_ALLOWED_ORIGIN port / omitting it
